name: push-action
on: [push]

jobs:
  exec-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v3
        with:
          ruby-version: "3.1.1"
      - run: npm bundler install
      - run: bundle exec rspec
